[33.955812454] 2018-10-21 03:18:43,787 - INFO - launcher: Starting sanity checks
[34.454822540] 2018-10-21 03:18:43,788 - INFO - launcher: Checking for Python 3.5+
[34.454822540] 2018-10-21 03:18:43,788 - INFO - launcher: Checking console encoding
[34.954309464] 2018-10-21 03:18:43,788 - INFO - launcher: Setting console encoding to UTF-8
[34.954309464] 2018-10-21 03:18:43,788 - INFO - launcher: Ensuring we're in the right environment
[35.953044891] 2018-10-21 03:18:43,789 - INFO - launcher: Adding local bins/ folder to path
[1257.351160049] 2018-10-21 03:18:45,011 - INFO - launcher: Required checks passed.
[1261.348247528] 2018-10-21 03:18:45,015 - INFO - launcher: Optional checks passed.
[1261.845111847] 2018-10-21 03:18:45,015 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.8420846462249756] 2018-10-21 03:18:45,596 - INFO - musicbot.config | In config.py::MainThread(12240), line 124 in run_checks: Using i18n: config/i18n/kr.json
[1.8450806140899658] 2018-10-21 03:18:45,599 - DEBUG - musicbot.json | In json.py::MainThread(12240), line 8 in __init__: Init JSON obj with config/i18n/kr.json
[2.4048464298248291] 2018-10-21 03:18:46,158 - DEBUG - musicbot.bot | In bot.py::MainThread(12240), line 223 in _setup_logging: Set logging level to INFO
[2.4048464298248291] 2018-10-21 03:18:46,158 - INFO - musicbot.bot | In bot.py::MainThread(12240), line 83 in __init__: Starting MusicBot 1.9.8_1
[2.4053461551666260] 2018-10-21 03:18:46,159 - INFO - musicbot.bot | In bot.py::MainThread(12240), line 89 in __init__: Loaded autoplaylist with 35 entries
[5.4390578269958496] 2018-10-21 03:18:49,193 - DEBUG - musicbot.bot | In bot.py::MainThread(12240), line 913 in on_ready: Connection established, ready to go.
[5.4395570755004883] 2018-10-21 03:18:49,193 - DEBUG - musicbot.bot | In bot.py::MainThread(12240), line 334 in _cache_app_info: Caching app info
[5.6508026123046875] 2018-10-21 03:18:49,404 - DEBUG - musicbot.bot | In bot.py::MainThread(12240), line 735 in _scheck_ensure_env: Ensuring data folders exist
[5.6517999172210693] 2018-10-21 03:18:49,405 - DEBUG - musicbot.bot | In bot.py::MainThread(12240), line 751 in _scheck_server_permissions: Checking server permissions
[5.6523008346557617] 2018-10-21 03:18:49,406 - DEBUG - musicbot.bot | In bot.py::MainThread(12240), line 755 in _scheck_autoplaylist: Auditing autoplaylist
[5.6523008346557617] 2018-10-21 03:18:49,406 - DEBUG - musicbot.bot | In bot.py::MainThread(12240), line 759 in _scheck_configs: Validating config
[5.6523008346557617] 2018-10-21 03:18:49,406 - DEBUG - musicbot.config | In config.py::MainThread(12240), line 213 in async_validate: Validating options...
[5.6523008346557617] 2018-10-21 03:18:49,406 - DEBUG - musicbot.bot | In bot.py::MainThread(12240), line 762 in _scheck_configs: Validating permissions config
[5.6523008346557617] 2018-10-21 03:18:49,406 - DEBUG - musicbot.permissions | In permissions.py::MainThread(12240), line 65 in async_validate: Validating permissions...
[5.6523008346557617] 2018-10-21 03:18:49,406 - INFO - musicbot.bot | In bot.py::MainThread(12240), line 930 in on_ready: Connected: 353925960497889280/뿌까봇#2846
[5.6532900333404541] 2018-10-21 03:18:49,407 - INFO - musicbot.bot | In bot.py::MainThread(12240), line 938 in on_ready: Owner:     353925449690382337/뿌까#8092

[5.6532900333404541] 2018-10-21 03:18:49,407 - INFO - musicbot.bot | In bot.py::MainThread(12240), line 941 in on_ready: Guild List:
[5.6537892818450928] 2018-10-21 03:18:49,407 - INFO - musicbot.bot | In bot.py::MainThread(12240), line 944 in on_ready:  - 바보개
[5.6537892818450928] 2018-10-21 03:18:49,407 - INFO - musicbot.bot | In bot.py::MainThread(12240), line 944 in on_ready:  - 뿌까 좋아?
[5.6542882919311523] 2018-10-21 03:18:49,408 - INFO - musicbot.bot | In bot.py::MainThread(12240), line 944 in on_ready:  - arete
[5.6542882919311523] 2018-10-21 03:18:49,408 - INFO - musicbot.bot | In bot.py::MainThread(12240), line 990 in on_ready: Not bound to any text channels
[5.6547880172729492] 2018-10-21 03:18:49,408 - INFO - musicbot.bot | In bot.py::MainThread(12240), line 1006 in on_ready: Not autojoining any voice channels
